export type CountryStateCombo = { combo: string; name: string }

export const ALL_COUNTRY_STATE_COMBOS: CountryStateCombo[] = [
  { combo: "ca-ab", name: "Alberta" },
  { combo: "ca-bc", name: "British Columbia" },
  { combo: "ca-mb", name: "Manitoba" },
  { combo: "ca-nb", name: "New Brunswick" },
  { combo: "ca-nl", name: "Newfoundland and Labrador" },
  { combo: "ca-ns", name: "Nova Scotia" },
  { combo: "ca-nt", name: "Northwest Territories" },
  { combo: "ca-nu", name: "Nunavut" },
  { combo: "ca-on", name: "Ontario" },
  { combo: "ca-pe", name: "Prince Edward Island" },
  { combo: "ca-qc", name: "Quebec" },
  { combo: "ca-sk", name: "Saskatchewan" },
  { combo: "ca-yt", name: "Yukon" },
  { combo: "us-al", name: "Alabama" },
  { combo: "us-ak", name: "Alaska" },
  { combo: "us-az", name: "Arizona" },
  { combo: "us-ar", name: "Arkansas" },
  { combo: "us-ca", name: "California" },
  { combo: "us-co", name: "Colorado" },
  { combo: "us-ct", name: "Connecticut" },
  { combo: "us-de", name: "Delaware" },
  { combo: "us-dc", name: "District of Columbia" },
  { combo: "us-fl", name: "Florida" },
  { combo: "us-ga", name: "Georgia" },
  { combo: "us-hi", name: "Hawaii" },
  { combo: "us-id", name: "Idaho" },
  { combo: "us-il", name: "Illinois" },
  { combo: "us-in", name: "Indiana" },
  { combo: "us-ia", name: "Iowa" },
  { combo: "us-ks", name: "Kansas" },
  { combo: "us-ky", name: "Kentucky" },
  { combo: "us-la", name: "Louisiana" },
  { combo: "us-me", name: "Maine" },
  { combo: "us-md", name: "Maryland" },
  { combo: "us-ma", name: "Massachusetts" },
  { combo: "us-mi", name: "Michigan" },
  { combo: "us-mn", name: "Minnesota" },
  { combo: "us-ms", name: "Mississippi" },
  { combo: "us-mo", name: "Missouri" },
  { combo: "us-mt", name: "Montana" },
  { combo: "us-ne", name: "Nebraska" },
  { combo: "us-nv", name: "Nevada" },
  { combo: "us-nh", name: "New Hampshire" },
  { combo: "us-nj", name: "New Jersey" },
  { combo: "us-nm", name: "New Mexico" },
  { combo: "us-ny", name: "New York" },
  { combo: "us-nc", name: "North Carolina" },
  { combo: "us-nd", name: "North Dakota" },
  { combo: "us-oh", name: "Ohio" },
  { combo: "us-ok", name: "Oklahoma" },
  { combo: "us-or", name: "Oregon" },
  { combo: "us-pa", name: "Pennsylvania" },
  { combo: "us-ri", name: "Rhode Island" },
  { combo: "us-sc", name: "South Carolina" },
  { combo: "us-sd", name: "South Dakota" },
  { combo: "us-tn", name: "Tennessee" },
  { combo: "us-tx", name: "Texas" },
  { combo: "us-ut", name: "Utah" },
  { combo: "us-vt", name: "Vermont" },
  { combo: "us-va", name: "Virginia" },
  { combo: "us-wa", name: "Washington" },
  { combo: "us-wv", name: "West Virginia" },
  { combo: "us-wi", name: "Wisconsin" },
  { combo: "us-wy", name: "Wyoming" }
]
