export type CountryStateCombo = { combo: string; name: string; desiredScrapeCount: number }

export const ALL_COUNTRY_STATE_COMBOS: CountryStateCombo[] = [
  { combo: "ca-ab", name: "Alberta", desiredScrapeCount: 2500 },
  { combo: "ca-bc", name: "British Columbia", desiredScrapeCount: 2500 },
  { combo: "ca-mb", name: "Manitoba", desiredScrapeCount: 2500 },
  { combo: "ca-nb", name: "New Brunswick", desiredScrapeCount: 2500 },
  { combo: "ca-nl", name: "Newfoundland and Labrador", desiredScrapeCount: 2500 },
  { combo: "ca-ns", name: "Nova Scotia", desiredScrapeCount: 2500 },
  { combo: "ca-nt", name: "Northwest Territories", desiredScrapeCount: 2500 },
  { combo: "ca-nu", name: "Nunavut", desiredScrapeCount: 2500 },
  { combo: "ca-on", name: "Ontario", desiredScrapeCount: 2500 },
  { combo: "ca-pe", name: "Prince Edward Island", desiredScrapeCount: 2500 },
  { combo: "ca-qc", name: "Quebec", desiredScrapeCount: 2500 },
  { combo: "ca-sk", name: "Saskatchewan", desiredScrapeCount: 2500 },
  { combo: "ca-yt", name: "Yukon", desiredScrapeCount: 2500 },
  { combo: "us-al", name: "Alabama", desiredScrapeCount: 2500 },
  { combo: "us-ak", name: "Alaska", desiredScrapeCount: 2500 },
  { combo: "us-az", name: "Arizona", desiredScrapeCount: 2500 },
  { combo: "us-ar", name: "Arkansas", desiredScrapeCount: 2500 },
  { combo: "us-ca", name: "California", desiredScrapeCount: 8000 }, // Higher than usual
  { combo: "us-co", name: "Colorado", desiredScrapeCount: 2500 },
  { combo: "us-ct", name: "Connecticut", desiredScrapeCount: 2500 },
  { combo: "us-de", name: "Delaware", desiredScrapeCount: 2500 },
  { combo: "us-dc", name: "District of Columbia", desiredScrapeCount: 2500 },
  { combo: "us-fl", name: "Florida", desiredScrapeCount: 6000 }, // Higher than usual
  { combo: "us-ga", name: "Georgia", desiredScrapeCount: 2500 },
  { combo: "us-hi", name: "Hawaii", desiredScrapeCount: 2500 },
  { combo: "us-id", name: "Idaho", desiredScrapeCount: 2500 },
  { combo: "us-il", name: "Illinois", desiredScrapeCount: 2500 },
  { combo: "us-in", name: "Indiana", desiredScrapeCount: 2500 },
  { combo: "us-ia", name: "Iowa", desiredScrapeCount: 2500 },
  { combo: "us-ks", name: "Kansas", desiredScrapeCount: 2500 },
  { combo: "us-ky", name: "Kentucky", desiredScrapeCount: 2500 },
  { combo: "us-la", name: "Louisiana", desiredScrapeCount: 2500 },
  { combo: "us-me", name: "Maine", desiredScrapeCount: 2500 },
  { combo: "us-md", name: "Maryland", desiredScrapeCount: 2500 },
  { combo: "us-ma", name: "Massachusetts", desiredScrapeCount: 2500 },
  { combo: "us-mi", name: "Michigan", desiredScrapeCount: 2500 },
  { combo: "us-mn", name: "Minnesota", desiredScrapeCount: 2500 },
  { combo: "us-ms", name: "Mississippi", desiredScrapeCount: 2500 },
  { combo: "us-mo", name: "Missouri", desiredScrapeCount: 2500 },
  { combo: "us-mt", name: "Montana", desiredScrapeCount: 2500 },
  { combo: "us-ne", name: "Nebraska", desiredScrapeCount: 2500 },
  { combo: "us-nv", name: "Nevada", desiredScrapeCount: 2500 },
  { combo: "us-nh", name: "New Hampshire", desiredScrapeCount: 2500 },
  { combo: "us-nj", name: "New Jersey", desiredScrapeCount: 2500 },
  { combo: "us-nm", name: "New Mexico", desiredScrapeCount: 2500 },
  { combo: "us-ny", name: "New York", desiredScrapeCount: 2500 },
  { combo: "us-nc", name: "North Carolina", desiredScrapeCount: 2500 },
  { combo: "us-nd", name: "North Dakota", desiredScrapeCount: 2500 },
  { combo: "us-oh", name: "Ohio", desiredScrapeCount: 2500 },
  { combo: "us-ok", name: "Oklahoma", desiredScrapeCount: 2500 },
  { combo: "us-or", name: "Oregon", desiredScrapeCount: 2500 },
  { combo: "us-pa", name: "Pennsylvania", desiredScrapeCount: 2500 },
  { combo: "us-ri", name: "Rhode Island", desiredScrapeCount: 2500 },
  { combo: "us-sc", name: "South Carolina", desiredScrapeCount: 2500 },
  { combo: "us-sd", name: "South Dakota", desiredScrapeCount: 2500 },
  { combo: "us-tn", name: "Tennessee", desiredScrapeCount: 2500 },
  { combo: "us-tx", name: "Texas", desiredScrapeCount: 8000 }, // Higher than usual
  { combo: "us-ut", name: "Utah", desiredScrapeCount: 2500 },
  { combo: "us-vt", name: "Vermont", desiredScrapeCount: 2500 },
  { combo: "us-va", name: "Virginia", desiredScrapeCount: 2500 },
  { combo: "us-wa", name: "Washington", desiredScrapeCount: 2500 },
  { combo: "us-wv", name: "West Virginia", desiredScrapeCount: 2500 },
  { combo: "us-wi", name: "Wisconsin", desiredScrapeCount: 2500 },
  { combo: "us-wy", name: "Wyoming", desiredScrapeCount: 2500 }
]
